### ISSUE TITLE
NoMethodError: undefined method `extract_event' for Lograge::Sql:Module

### ISSUE THREAD

**Issue by mrlevitas** [iMacTia/lograge-sql#6] opened 2019-04-02 19:35 UTC
```
Could not log "sql.active_record" event. 
NoMethodError: undefined method `extract_event' for Lograge::Sql:Module [".rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/lograge-sql-0.3.0/lib/lograge/sql/extension.rb:28:in `sql'", ".rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/activesupport-5.2.2/lib/active_support/subscriber.rb:101:in `finish'"
```

**Comment by iMacTia** [comment] 2019-04-03 07:12
Hi, thanks for raising this.
I suspect this is an incompatibility with latest Ruby/Rails versions since the gem have not been updated for a while.
Could you please give more details of your Gemfile.lock and specifically:
* Ruby version
* Rails version
* Lograge version

Apologies in advance if it will take me a while to look into this, as I’m travelling at the moment

**Comment by mrlevitas** [comment] 2019-04-04 22:26
thanks for the response

ruby 2.4.5
rails 5.2.2
lograge 0.10.0

**Comment by iMacTia** [comment] 2019-04-05 06:45
Thanks for the details!
I hope I’ll be able to have a look at some point next week. Feel free to nudge me if you don’t hear back from me :)

**Comment by iMacTia** [comment] 2019-04-10 12:25
@mrlevitas mmmh just opening the console and `Lograge::Sql.extract_event` works fine.
I suspect your issue is that `lograge/sql/extension` is loaded but `lograge/sql` is not.
Although in theory, adding it to the gemfile should load it automatically.
Did you explicitly stop that with a `require: false` in the Gemfile?
Is your project Open Source so I can give it a look?

**Comment by iMacTia** [comment] 2019-05-07 11:14
@mrlevitas I'm closing this as I wasn't able to reproduce and I suspect it's just a loading issue.
Happy to reopen if you can provide additional info

**Closed by iMacTia** 2019-05-07 11:14 UTC
Labels: unconfirmed

**Comment by zzerjae** [comment] 2019-08-22 03:50
i have also this issue.

**Comment by iMacTia** [comment] 2019-08-22 12:04
@zzerjae when I tried replicating this I wasn't able to. If you could help me to consistently reproduce it somehow, I'd be able to investigate it further.

**Comment by zzerjae** [comment] 2019-08-22 12:19
my versions:
- ruby 2.6.3
- rails 5.2.3
- lograge 0.11.2
- lograge-sql 0.4.0

In my case, I can resolve it like this.

```ruby
# config.lograge_sql.extract_event = Proc.new do |event|
Lograge::Sql.extract_event = Proc.new do |event|
  { name: event.payload[:name], duration: event.duration.to_f.round(2), sql: event.payload[:sql] }
end
# config.lograge_sql.formatter = Proc.new do |sql_queries|
Lograge::Sql.formatter = Proc.new do |sql_queries|
  sql_queries
end
```

I think, this issue does not seem to be caused by lograge-sql gem.
I'm not sure, but I think my rails initial setup config has a problem.

**Comment by iMacTia** [comment] 2019-08-22 12:23
Thanks for the details @zzerjae. As I mentioned above, I believe this is a loading order issue rather an issue with the code itself:
> I suspect your issue is that lograge/sql/extension is loaded but lograge/sql is not.

There are many reasons why that might happen, so it's hard to point you in the right direction, but one would be to use a local copy of `lograge-sql` and add some debug messages at the beginning of each file to check the loading order. There might be something in your project causing `lograge/sql/extension` to be loaded prematurely or `lograge/sql` to not be loaded for some reason.

**Comment by zzerjae** [comment] 2019-08-22 12:28
Thank you for your attention to closed issues. I will comment again if there is any clarification.
I appreciate for creating and managing this gem.:)
